/* tslint:disable */
/* eslint-disable */
/**
 * Indiebackend Admin API
 * Indiebackend API documentation for admins & game developpers
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

